name: main

on:
  push:
    branches:
    - main

jobs:
  gh-pages:
    runs-on: macos-15

    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Build Publish
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        make install

    - name: Generate Site
      run: publish generate

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Output
