name: Deploy

on:
  push:
    branches:
      - main

jobs:
  gh-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.1
        bundler-cache: true

    - name: Build
      run: |
        bundle config set --local path 'gems_cache'
        bundle install
        bundle exec jekyll build
        make generate-privacy-policies

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
